---
- name: database assignment
  hosts: db
  ansible.builtin.import_playbook: ../static-assignments/database.yml

- name: nginx assignment
  hosts: nginx
  ansible.builtin.import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
#   name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

- name: sonar assignment
  hosts: sonar
  ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
#   name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml
